services:
  postgres:
    image: postgres:18
    container_name: portfolio-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portfolio

    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - portfolio

volumes:
  postgres_data:

networks:
  portfolio: